codecov:
  token: 18ee63ca-bda4-4eac-ad56-5338fbf17f51

coverage:
    range: 80..100
    round: down
    precision: 2

    status:
        project:
            default:
                enabled: yes
                target: auto

                threshhold: 1%
                if_not_found: success
                if_ci_failed: error
            patch:
                default:
                    enabled: no


ignore:
    - "test/*"
